server:
  port: 9092
spring:
  application:
    name: service-b
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
    net.app.opentelemetry.service.b: debug
    org.springframework: info

opentracing:
  jaeger:
    expand-exception-logs: true
    log-spans: true
#    udp-sender:
#      host: lslogcpm001.hms.hmsy.com
